// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:86a85472-f201-4575-8f82-48d0a96b6f28',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '1e97c4e87b764e82b7979060e0f024e7',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7842fc2c-e558-4baf-b76d-1d950a325333',
    'aws_project_name': 'journal',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'journal-mobilehub-1045334791',
}

export default awsmobile;
